# -*- coding: utf-8 -*-
"""LVADSUSR151_dheeraj_lab_4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Vrik-8cY_TkeoakSGRXT6_Zlr5w7HNBj
"""

import pandas as pd
from matplotlib import pyplot as plt
import seaborn as sns
from sklearn.ensemble import IsolationForest
import warnings
warnings.filterwarnings('ignore')

df = pd.read_csv('/content/anomaly_train (1).csv')

df.head()

df.describe()

df.info()

df.isnull().sum()

sns.violinplot(df, x='Type', y='Amount', inner='stick', palette='Dark2')
sns.despine(top=True, right=True, bottom=True, left=True)

df.head()

features = ["Amount", "Time", "User"]
X = df[features]
model = IsolationForest()
model.fit(X)
y_pred = model.predict(X)

df["anomaly_score"] = model.decision_function(X)

plt.scatter(df["Amount"], df["anomaly_score"], label="Not Anomaly")