# -*- coding: utf-8 -*-
"""Untitled10.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ncXEcsOw1H2TccPtZMhnx3U-ksxIdqjU
"""

# 1
def area_cal(lenght,breath):
  t_area = lenght*breath
  print(f'Total Area= {t_area} m_square')
  if t_area <3000:
    print("small Area")
  elif t_area < 6000:
    print("Medim Area")
  else:
    print("Large Area")

l = int(input('enter lenght of land in meter:'))
b =  int(input('enter breadth of land in meter:'))
area_cal(l,b)

# 2
w= float(input('enter your weight in kg = '))
h = float(input('enter your height in meter = '))
print('your BMI is = ',w/h**2)

# 3
class Student:
  def __init__(self,roll,name,numbers= 0):
    self.roll = roll
    self.name = name
    self.numbers = {'sub1': None,"sub2": None,"sub3": None,"Sub4": None}
    for x in self.numbers.keys():
      self.numbers[x] = int(input(print(f'enter for {x} =')))

  def report(self):
    print('Name:',self.name)
    grade = sum(self.numbers.values())/400*100
    print('grade=',grade)

stu1 = Student(12,'Dheeraj')
stu1.report()

# lab 2

#1
def recco(age):
  if age < 13:
   print('here are your Shows: ')
   print('best child shows:')
  elif age < 19:
     print('here are your Shows: ')
     print('best teen shows:')
  elif age< 30:
     print('here are your Shows: ')
     print('best adult shows:')
  else :
     print('here are your Shows: ')
     print('best senior shows:')


age= int(input('enter age:'))
recco(age)

# 2
sub_id= [1,2,3,4,5,6,7,78,8]
even= []
for x in sub_id:
  if x%2 == 0:
    even.append(x)
print(even)

# 6
passw = input('enter password')
correct = 'right'
if passw == correct:
  print("welcome")

# 7
import math
lists = [7,8,9,8,7,6,7,8,9]
def scores(lis):
  avg_score = sum(lis)/len(lis)
  print('average score :',avg_score )

scores(lists)

# 8
com = {1:"comments good bads",2:'normal not so excited'}
count= 0
for x in com.items():
  for y in com[x]:
    if y in('a','e','i','o','u'):
      count += 1
print('vovel count = ',count)

# 9
import datetime
date = datetime.datetime
print(date)
print("enjoy your daay")

# 10
intrest = 3.5
l_interest = 10
amount = 50000
try:
  print('saving intreasts :',amount*intrest/100)
  print('loan intrests : ',amount *l_interest/100)
except ZeroDivisionError:
  Pass

# 11
from logging import NullHandler
rating = int(input('your entry ='))
 try:
   type(rating) == int:
   prin('good')
  except NullHandler:
    pass

# 12
value = input('get')
try:
   type(rating) == int:
   print('rate',400/value)
  except ZeroDivisionError:
    print('value cant be zero')