# -*- coding: utf-8 -*-
"""Dheeraj_final.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PJmo2JII3MxOmej1wunZsfoeCbHPVAX8
"""

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

"""LAB 1

////A/////
"""

df = pd.read_csv(r'https://raw.githubusercontent.com/Deepsphere-AI/LVA-Batch5-Assessment/main/Final%20Dataset%20-%20IPL.csv')
df

# ////B/////
df.describe()

df.info()

"""dtaset have no null value in any of the columns.

**2:data cleaning**
"""

df.info()

"""As the data set is not having any null value as we check with the info() function. thus it is ready to go for the next step.

3:Descriptive
"""

dd=df.describe()
dd

"""results: like heighest score in first inning = 222
lowest score in first inning  = 68
         
"""

from matplotlib import pyplot as plt
dd['first_ings_score'].plot(kind='line', figsize=(8, 4), title='first_ings_wkts')
plt.gca().spines[['top', 'right']].set_visible(False)

"""from the above line plot about is giving info abouts the first inning statastics data like count mean etc.

**4:Data Visualization**
"""

df
df['match_winner'].value_counts().plot()
plt.xlabel("Teams")
plt.ylabel('Wins')
plt.title('MAximum Wins')

"""from the above line plot is is observed that gujrathas wins maximum matches 12."""

from matplotlib import pyplot as plt
import seaborn as sns
df.groupby('venue').size().plot(kind='barh', color=sns.palettes.mpl_palette('Dark2'))
plt.gca().spines[['top', 'right',]].set_visible(False)

"""from the above graph about the numbers of the matches in different stadium it is showing maximum matches are held in Wankhede Stadium, Mumbai,followed by Dr DY Patil Sports Academy, Mumbai.

**5:Relationship**
"""

plt.figure(figsize=(14,9))
# ax= plt.add_axes(1,1,2,1)
plt.scatter(x=df['toss_winner'],y=df['match_winner'])
plt.xlabel('toss_winner')
plt.ylabel('match_winner')

"""no such relation ship
diagoa;l line is showing cases where team has woned both match and tosses.
"""

plt.subplots(figsize=(14, 8))
df_2dhist = pd.DataFrame({
    x_label: grp['won_by'].value_counts()
    for x_label, grp in df.groupby('toss_decision')
})
sns.heatmap(df_2dhist, cmap='viridis')
plt.xlabel('toss_decision')
_ = plt.ylabel('won_by')

"""the above subplot is showing relationship between toss descision and won by from which one can tell that when a teams chooses to bat first after winning a toss on an average he wons by run around 2 to 8
and they cjoose to feild first they have wins the match by around 25 to 30 runs.
"""

# toss wins and decision
df.groupby('toss_decision').size().plot(kind='bar', color=sns.palettes.mpl_palette('Dark2'))
plt.ylabel('counts')
plt.title('Dicisions')

"""from the above plot whenever a team wins the toss maximun teams sre prefering to feild first this shows that most team like to chase in second innings ."""

plt.scatter(x=df['first_ings_score'],y=df['first_ings_wkts'])
plt.title('first Inning and their score')
plt.xlabel('Score')
plt.ylabel('wickets losed')

"""this visualizatoion tells that in the first inning of the match as the wickets losed by the team increases their total score got dereses
thus it is iportant to save the wickets to get a good score .

**6: Outliers**
"""

plt.hist(x=df['highscore'],bins =20)

plt.scatter(x=df['first_ings_score'],y=df['first_ings_wkts'])

"""in above graph one exception where score is high even though wicket loss is high despite inverse  relationship between them.

but as it cricket game this types of little outliers are normal so i will keep it and don't remove the data.

7:performance trends
"""

plt.figure(figsize=(14,9))
df['match_winner'].value_counts().plot.pie(autopct='%1.1f%%')
plt.title('Team Wins Percentage')
plt.ylabel('')

"""gujrat has wined max match percet with 16.2%"""

sns.histplot(data=df, x='highscore', bins=30, kde=True)
plt.title('High Distributions')

"""most batmans are making highscore in range of 50 to 80 there are also highscore of more than 100 but that has occure only trice means that are exceptions.

8:Player Spotlight
"""

plt.figure(figsize=(14,9))
df['player_of_the_match'].value_counts().plot()
        #  df['match_winner'].value_counts().plot.pie(autopct='%1.1f%%')

"""Kuldeep Yadav has won the Player of the match title for maximum 4 times among other players.

9:Summery

* from analysis performed above followings are my finding from the dataset given:

1. Gujrat has woned title of winner maximum times that other teams.
2. Kuldeep Yadav Has woned maximun Player of the match 4 times
3. chances of winning increses whem team chooses to feild first .
4. maximum 20 matches has been played in wankhde stadium.
"""

df
df['match_winner'].value_counts().plot()
plt.xlabel("Teams")
plt.ylabel('Wins')
plt.title('MAximum Wins')