# -*- coding: utf-8 -*-
"""LVADSUSR151_dheeraj_log.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sppZnTFDKAUYD8zDcMgyMqv-g4MCd--d
"""

# problem 2
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import MinMaxScaler

df = pd.read_csv('/content/booking.csv')

df.info()

df.shape

df.describe()

df.isnull().sum()

df.fillna(df['room type'].mode(),inplace=True)
df.fillna(df['average price'].mean(),inplace=True)

plt.boxplot(df['average price'])

df.head()

dummies=['type of meal','market segment type','room type','booking status']
df=pd.get_dummies(df,columns=dummies,drop_first =True)

df.head()

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
model = LogisticRegressionRegression()
model.fit(X_train, y_train)

y_pred = model.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)
confusion_matrix(y_test,y_pred)
print(classification_report(y_test, y_pred))





